"""add created_at to message table

Revision ID: 26c74095972b
Revises: 63cc24b6f4fe
Create Date: 2024-05-21 18:31:46.375014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26c74095972b'
down_revision = '63cc24b6f4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'created_at')
    # ### end Alembic commands ###
